[tool.poetry]
name = "animal-app"
version = "0.1.0"
description = ""
authors = ["slocksert <rsdlj01@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.111.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
